services:
  - type: web
    name: python-special-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --threads=8 --timeout=300
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      # AI API Keys - Set these in Render dashboard
      - key: GOOGLE_GEMINI_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      # Database Configuration - Set these in Render dashboard
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DATABASE
        sync: false
      # Flask Configuration
      - key: FLASK_SECRET_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: USE_PURE
        value: "True"

